name: CI

on:
    push:
    pull_request:

jobs:
    phpunit:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                include:
                    -   php: '8.1'
                        psalm: true
                    -   php: '8.1'
                        phpunit: '8.5'
                    -   php: '8.5'
                        psalm: true
                    -   php: '8.5'
                        phpunit: '8.5'
        steps:
            -   uses: actions/checkout@v6

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: 'composer:v2'

            -   name: Cache Composer dependencies
                uses: actions/cache@v5
                with:
                    path: '~/.composer/cache'
                    key: ${{ runner.os }}-php${{ matrix.php }}-phpunit${{ matrix.phpunit }}-symfony${{ matrix.symfony }}-${{ hashFiles('**/composer.json') }}

            -   name: Install dependencies with composer
                env:
                    SYMFONY_REQUIRE: ${{ matrix.symfony }}
                run: composer update --no-interaction --no-progress

            -   name: Run test suite
                uses: php-actions/phpunit@v4
                if: ${{ matrix.phpunit != '' }}
                with:
                    php_version: ${{ matrix.php }}
                    version: ${{ matrix.phpunit }}

            -   name: Run Psalm analysis
                run: vendor/bin/psalm
                if: ${{ matrix.psalm == true }}
                continue-on-error: true
